FinalFantasyProject/FinalFantasyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('games/', include("games.urls")),

    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

FinalFantasyProject/games/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = "games"

urlpatterns = [

    path("", views.index, name="index"),
    path("<int:game_id>/", views.game_details, name="game_details"),

    path("characters/", views.character_list, name="character_list"),

    path("characters/<int:character_id>", views.character_details, name="character_details"),

    path("genres/", views.genre_list, name="genre_list")

]

FinalFantasyProject/games/models.py
from django.db import models

# Create your models here.


from django.db import models

class Game(models.Model):
    title = models.CharField(max_length=200)
    release_date = models.DateField("release date")
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE)
    description = models.TextField()
    def __str__(self):
        return self.title


class Character(models.Model):
    name = models.CharField(max_length=200)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    jobs = models.ForeignKey('Job', on_delete=models.CASCADE)
    character_description = models.TextField()
    def __str__(self):
        return self.name

class Genre(models.Model):
    genre_name = models.CharField(max_length=50)
    def __str__(self):
        return self.genre_name

class Job(models.Model):
    job_name = models.CharField(max_length=50)
    job_description = models.TextField()
    def __str__(self):
        return self.job_name








FinalFantasyProject/games/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

# Create your views here.

from django.http import HttpResponse

from games.models import Game, Character, Genre, Job

@login_required
def index(request):

    game = Game.objects.all()
    context = {'games' : game }
    return render(request, 'games/index.html', context)


@login_required
def game_details(request, game_id):

    game = Game.objects.get(pk=game_id)
    context = {'game' : game }
    return render(request, 'games/game_details.html', context)
@login_required
def character_details(request, character_id):
    character = get_object_or_404(Character, id=character_id)
    context = {'character': character}
    return render(request, 'games/character_details.html', context)

@login_required
def character_list(request):

    characters = Character.objects.all()
    context = {'characters' : characters}
    return render(request, 'games/character_list.html', context)

@login_required
def genre_list(request):
    genres = Genre.objects.all()
    context = {'genres' : genres}
    return render(request,'games/genre_list.html',context)

@login_required
def job_list(request):
    jobs = Job.objects.all()
    context = {'jobs' : jobs}
    return render(request, 'games/job_list.html',context)







FinalFantasyProject/templates/games/character_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Character Details</title>
</head>
<body>
    <h1>Character Details</h1>
    <ul>
        <li>Name: {{ character.name }}</li>
        <li>Jobs: {{ character.jobs }}</li>
        <li>Description: {{ character.character_description }}</li>
    </ul>
    <a href="{% url 'games:index' %}">Back to game list</a>
</body>
</html>

FinalFantasyProject/templates/games/character_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

   <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Characters</title>
</head>
<body>
    <h1>Characters</h1>
    <ul>
        {% for character in characters %}
            <li>{{ character.name }}</li>
        {% empty %}
            <li>No genres available.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'games:index' %}">Back to game list</a>
</body>
</html>

</body>
</html>

FinalFantasyProject/templates/games/game_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    
    <h1>Game details: {{ game.title }}</h1>
    
    <ul>
        <li>Title: {{ game.title }}</li>
        <li>Release date : {{ game.release_date }}</li>
        <li>Genre: {{ game.genre }}</li>
        <li>Description: {{ game.description }}</li>
        <h2>Personajes</h2>
   
        {% for character in game.character_set.all %}
            <li>
                <a href="{% url 'games:character_details' character.id %}">{{ character.name }} ({{ character.jobs }})</a>
            </li>
        {% empty %}
            <li>No hay personajes disponibles para este juego.</li>
        {% endfor %}
    </ul>
    
    <a href="{% url 'games:index' %}">Volver a la lista de juegos</a>
            
       
        
       



</body>
</html>

FinalFantasyProject/templates/games/games_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

FinalFantasyProject/templates/games/genre_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Genres</title>
</head>
<body>
    <h1>Genres</h1>
    <ul>
        {% for genre in genres %}
            <li>{{ genre.genre_name }}</li>
        {% empty %}
            <li>No genres available.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'games:index' %}">Back to game list</a>
</body>
</html>

FinalFantasyProject/templates/games/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <h1>Final Fantasy Wiki</h1>
    <ul>
        {% for game in games %}
            <h3><a href="{% url 'games:game_details' game.id %}"> {{ game.title }} ({{ game.release_date }})</a></h3>
        {% endfor %}
    </ul>

    <a href="{% url 'games:genre_list'  %}">Genres of the saga</a>
    <br>
    <a href="{% url 'games:character_list' %}">Todos los personajes</a>

</body>
</html>

FinalFantasyProject/templates/games/job_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>